<a href="https://colab.research.google.com/github/kim-hyun-ho/study/blob/main/210330.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy

In [6]:
import numpy as np

A = [1,2,3,4]
a = np.array(A,np.int)

print('a의 차원 :',a.ndim)
print(a)
b=np.array([1])
print('b의 차원 : ',b.ndim)
print(b)

a의 차원 : 1
[1 2 3 4]
b의 차원 :  1
[1]


In [16]:
arr6 = np.array([[1,2],[3,4]])
arr6 = np.array(((1,2),(3,4)))
print(arr6)

[[1 2]
 [3 4]]


In [ ]:
#주요 함수
#zero : 0으로 초기화
#ones : 1로 초기화
#full : 특정 값으로 초기화
#empty : 초기화 되지 않은 배열을 생성
#identity, eye : NxN의 단위행렬 : 대각선 값 1
#_likes : 주어진 배열과 같은 shape의 배열 생성
#arange : range와 유사 범위와 setpsize
#linspace : range와 유사 sample 갯수

In [28]:
np.zeros((5))
np.zeros((2,4),dtype=np.int8)
np.ones((3,3))
np.full((4),5)
np.full((2,5),-1.0)
np.empty((2,3),dtype=np.float64)

np.identity(5,dtype=int) #단위행렬 : 정방행렬만 가능

np.eye(5,dtype=int)

np.eye(5,10,dtype=int,k=5) #eye는 NxM 행렬 가능


np.arange(5)

array([0, 1, 2, 3, 4])

In [39]:
#배열 결합함수
#Hstack, concatenate(axis=0)

a=np.array((1,2,3))
b=np.array((4,5,6))
np.hstack((a,b)) #열로 붙임
np.vstack((a,b)) #행으로 붙임

np.concatenate((a,b),axis=0) #열로 붙임
# np.concatenate((a,b),axis=1) #에러 1차원은 지원 안함. 2차원은 됨.


array([1, 2, 3, 4, 5, 6])

In [42]:
np.column_stack([a,b]) # 1차원 행렬을 컬럼으로 붙임.


array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
#랜덤
import random
random.random() # 0<=리턴<1.0

#시드 넘버 지정, 같은 난수 나오게 하기 위해.
#재현가능성.

np.random.randn(10000)
#정규분포로 나옴.


array([ 0.0220252 ,  0.0543001 , -1.00192861, ..., -0.94113509,
        0.59173379, -0.05725877])

In [57]:
#연습
val = int(input('로또 번호를 몇개 생성 할까요? '))
for i in range(val):
    lnum = [ np.random.randint(1,46) for x in range(6)]
    lnum.sort()
    #print(lnum)
    snum = [ ' '+str(x) if x<10 else ''+str(x) for x in lnum]
    print(snum)


로또 번호를 몇개 생성 할까요? 5
[' 4', ' 8', '13', '13', '17', '40']
[' 3', '11', '15', '22', '24', '44']
[' 7', ' 9', '23', '34', '40', '45']
[' 1', ' 9', '21', '24', '36', '44']
[' 8', '19', '19', '22', '29', '45']


In [59]:
#flatten 납작하게 1차원으로 만들어 버림.
arr = np.zeros((3,2))
arr.flatten()

array([0., 0., 0., 0., 0., 0.])

In [72]:
#reshape 모양 변경 , 약수로 가능
arr=np.arange(12)
arr.reshape(3,4)
# arr.reshape(1,3,4)

arr.reshape(2,-1) #한쪽만 선언해줘도 된다.
arr.reshape(-1,4) #한쪽만 선언해줘도 된다.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
#transpose :행렬 뒤바꿈

#swapaxes

a=np.arange(3).reshape(1,3)
print(a)
y=np.swapaxes(a,0,1) #0은 가장 높은 차수의 축, 2차원 / 1은 그다음, 즉 원소의 행과 열을 바꿈
print(y)


[[0 1 2]]
[[0]
 [1]
 [2]]


In [85]:
a=np.arange(6).reshape(1,2,3)
print(a)
print(a.shape)

x=np.swapaxes(a,1,2)#2차원 축과 1차원 축을 바꿔라.
print(x)

[[[0 1 2]
  [3 4 5]]]
(1, 2, 3)
[[[0 3]
  [1 4]
  [2 5]]]


In [ ]:
#transpose 다차원 연습할까?
#transpose  축(axis) 건드리지 마세요.
arr.transpose()
arr.T #위와 동일

In [93]:
#연습
#리스트로
list1=[x for x in range(21)]
print(list1)
arr1 = [ x for x in list1 if x%2==0 ]
print(arr1)
arr2 = [ x for x in list1 if x%2==1 ]
print(arr2)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [105]:
#연습 np 어레이.
arr1 = np.arange(0,21,2)
print(arr1)
arr2 = np.arange(1,21,2)
print(arr2)

##다른방법
arr0 = np.arange(0,21)
print(arr0)
#문법 스타일???? 요소중 조건에 맞는 것만 뽑기.
arr1=arr0[arr0%2==0]
arr2=arr0[arr0%2!=0]
print(arr1)
print(arr2)

[ 0  2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [111]:
#모양을 바꿔 보자
arr = np.arange(30).reshape(2,3,5)
print(arr)
print()
print(arr.flatten())
print()
print(arr.reshape(6,5).transpose())

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [112]:
##연습
arr = np.arange(24).reshape(2,4,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [162]:
arr=np.arange(30).reshape(3,2,5)
print(arr)
print('-------------------')
cond=np.array(['a','b','c'])
#arr = arr[cond!='b']
arr = arr[(cond=='a') | (cond=='c')] #cond 인덱스가 1 이것 먼저 오고, c인것 오고
# arr = arr[cond=='a' | cond=='c'] #cond 이건 에러 위와 같이해야#
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
-------------------
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
#단항 유니버셜 함수
#exp 나 log 많이 쓰임


In [167]:
#이항 유니버셜함수
arr1=np.arange(8).reshape(2,-1)
arr2=np.arange(-40,40,10).reshape(2,-1)

In [168]:
arr1  

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [169]:
arr2

array([[-40, -30, -20, -10],
       [  0,  10,  20,  30]])

In [170]:
np.subtract(arr1,arr2) ###각원소 차

array([[ 40,  31,  22,  13],
       [  4,  -5, -14, -23]])

In [173]:
np.multiply(arr1,arr2) #### 각원소를 곱

array([[  0, -30, -40, -30],
       [  0,  50, 120, 210]])

In [175]:
arr = np.arange(4).reshape(2,-1)
arr

array([[0, 1],
       [2, 3]])

In [ ]:
#sum
#mean
#std 표준편차 , var 분산
#min,max
#argmin,argmax
#cumsum
#cumprod

#any
#all
#where
#sort

#선형대수

In [181]:
#dot : 내적
#dialog : 
#trace :
#linalg.det
#linalg.eig
#linalg.inv
#linalg.solve
#linalg.svd

a = np.arange(12).reshape(3,-1)
b = np.arange(28).reshape(4,-1)
print(a,'\n\n',b,'\n\n',np.dot(a,b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]] 

 [[ 98 104 110 116 122 128 134]
 [266 288 310 332 354 376 398]
 [434 472 510 548 586 624 662]]


In [ ]:
#판별식, 역행렬,

#고유값 eigen value
#고유벡터 eigen vector
#AX = 고유값x고유백터
#차원 축소 , 디콤포지션


In [182]:
i = np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [183]:
i=np.eye(3,5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [184]:
x=np.arange(9).reshape(3,-1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [185]:
np.diag(x)

array([0, 4, 8])

In [186]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [187]:
a=np.arange(4).reshape(-1,2)
print(a)

[[0 1]
 [2 3]]


In [188]:
print(a*a)

print(np.dot(a,a)) #내적은 b벡터는 a벡터 크기 곱하기 코사인 세타 : 정보 유사도 평가.

#3차이상 에서는 매트릭스 곱의 쓴다.
#np.matmul(a,b)


#단위행열 영행렬 역행렬 빼고는 교환법칙 성립하지 않는다.
#행렬 a dot b  != b dot a

[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]


In [ ]:
#trace 정방행렬의 대각에 위취하 원소를 전부더해줌

In [ ]:
#determin
#역행렬이 있는지
