<a href="https://colab.research.google.com/github/kim-hyun-ho/study/blob/main/%EC%8A%A4%EC%BC%80%EC%9D%BC%EB%A7%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# min_max
* MinMaxScaler

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

X=np.array([[10., -10.,1.],
            [5,0,2],
            [0,10,3]], dtype=float)
X

array([[ 10., -10.,   1.],
       [  5.,   0.,   2.],
       [  0.,  10.,   3.]])

In [2]:
X_MinMax = (X-X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_MinMax

array([[1. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [0. , 1. , 1. ]])

In [5]:
X=np.array([[10., -10.,1.],
            [5,0,2],
            [0,10,3]], dtype=float)
min_max_scaler = MinMaxScaler()
X_MinMax_train = min_max_scaler.fit_transform(X)

X_MinMax_train

array([[1. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [0. , 1. , 1. ]])

In [6]:
X_new=np.array([[9., -10.,1.],
            [5,-5,3],
            [1,0,5]], dtype=float)

X_MinMax_new = min_max_scaler.transform(X_new)

X_MinMax_new

array([[0.9 , 0.  , 0.  ],
       [0.5 , 0.25, 1.  ],
       [0.1 , 0.5 , 2.  ]])

In [10]:
#추가 학습
min_max_scaler.partial_fit(X_new)
X_MinMax_new = min_max_scaler.transform(X_new)

X_MinMax_new

array([[0.9 , 0.  , 0.  ],
       [0.5 , 0.25, 0.5 ],
       [0.1 , 0.5 , 1.  ]])

# 함수이용
* minmax_sacle()

In [11]:
from sklearn.preprocessing import minmax_scale
X=np.array([[10., -10.,1.],
            [5,0,2],
            [0,10,3]], dtype=float)

X_MinMax_scaled = minmax_scale(X, axis=0, copy=True)

X_MinMax_scaled

array([[1. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [0. , 1. , 1. ]])

# 표준정규분포 표준화
* Numpy : z= (x - mean())/std()
* scipy.stats : zscore()
* sklearn.preprocessing : StandardScaler().fit_transform()

In [28]:
import numpy as np

# data = np.random.randint(30, size=(6,5))
data = array([[ 1, 10, 16, 14,  7],
       [20, 13,  8, 21, 10],
       [13,  2, 17, 29,  2],
       [17, 19, 27,  5, 27],
       [ 8,  1, 12, 22, 12],
       [ 1, 27, 20, 26,  7]])
data

array([[ 1, 10, 16, 14,  7],
       [20, 13,  8, 21, 10],
       [13,  2, 17, 29,  2],
       [17, 19, 27,  5, 27],
       [ 8,  1, 12, 22, 12],
       [ 1, 27, 20, 26,  7]])

In [23]:
#Numpy : z=(x- mean())/std()

from numpy import *
data_standardized_np = (data - mean(data, axis=0)) / std(data, axis=0)

data_standardized_np

array([[-1.22474487, -0.21908902, -0.11128298, -0.68974894, -0.48759902],
       [ 1.36082763,  0.10954451, -1.4466787 ,  0.18811335, -0.10599979],
       [ 0.40824829, -1.09544512,  0.05564149,  1.19138454, -1.12359775],
       [ 0.95257934,  0.76681158,  1.72488614, -1.81842903,  2.05639589],
       [-0.27216553, -1.20498963, -0.77898084,  0.31352225,  0.1483997 ],
       [-1.22474487,  1.64316767,  0.55641488,  0.81515784, -0.48759902]])

In [14]:
mean(data_standardized_np, axis=0)

array([-1.85037171e-17,  0.00000000e+00,  9.25185854e-17,  3.70074342e-17,
       -9.25185854e-17])

In [15]:
std(data_standardized_np, axis=0)

array([1., 1., 1., 1., 1.])

In [16]:
#평균,표준편차,분산
import numpy as np
arr = np.array(range(11))
print('mean:', np.mean(arr))
print('standard deviation: ', np.std(arr))
print('variance: ', np.var(arr))

mean: 5.0
standard deviation:  3.1622776601683795
variance:  10.0


# scipy.stats :
* ss.zscore()

In [30]:
import scipy.stats as ss

data = array([[ 1, 10, 16, 14,  7],
       [20, 13,  8, 21, 10],
       [13,  2, 17, 29,  2],
       [17, 19, 27,  5, 27],
       [ 8,  1, 12, 22, 12],
       [ 1, 27, 20, 26,  7]])

data_standardized_ss = ss.zscore(data)

data_standardized_ss

array([[-1.22474487, -0.21908902, -0.11128298, -0.68974894, -0.48759902],
       [ 1.36082763,  0.10954451, -1.4466787 ,  0.18811335, -0.10599979],
       [ 0.40824829, -1.09544512,  0.05564149,  1.19138454, -1.12359775],
       [ 0.95257934,  0.76681158,  1.72488614, -1.81842903,  2.05639589],
       [-0.27216553, -1.20498963, -0.77898084,  0.31352225,  0.1483997 ],
       [-1.22474487,  1.64316767,  0.55641488,  0.81515784, -0.48759902]])

# sklearn.preprocessing :
* StandardScaler().fit_transform()


In [31]:
from sklearn.preprocessing import StandardScaler

data = array([[ 1, 10, 16, 14,  7],
       [20, 13,  8, 21, 10],
       [13,  2, 17, 29,  2],
       [17, 19, 27,  5, 27],
       [ 8,  1, 12, 22, 12],
       [ 1, 27, 20, 26,  7]])

data_standardized_skl = StandardScaler().fit_transform(data)

data_standardized_skl

array([[-1.22474487, -0.21908902, -0.11128298, -0.68974894, -0.48759902],
       [ 1.36082763,  0.10954451, -1.4466787 ,  0.18811335, -0.10599979],
       [ 0.40824829, -1.09544512,  0.05564149,  1.19138454, -1.12359775],
       [ 0.95257934,  0.76681158,  1.72488614, -1.81842903,  2.05639589],
       [-0.27216553, -1.20498963, -0.77898084,  0.31352225,  0.1483997 ],
       [-1.22474487,  1.64316767,  0.55641488,  0.81515784, -0.48759902]])