<a href="https://colab.research.google.com/github/kim-hyun-ho/study/blob/main/%ED%9D%AC%EC%86%8C%ED%96%89%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
from scipy import sparse


In [11]:
data = np.array([3,1,2])

#행 위치와 열 위치를 각각 생성
row_pos = np.array([0,0,1])
col_pos = np.array([0,2,1])

#sparse 패키지의  coo_matrix를 이용하여  coo  형식으로 희소행렬 생성
sparse_coo = "asdf"
sparse_coo = sparse.coo_matrix(((data,(row_pos,col_pos))))

print(type(sparse_coo))
print(sparse_coo)

<class 'scipy.sparse.coo.coo_matrix'>
  (0, 0)	3
  (0, 2)	1
  (1, 1)	2


In [13]:
sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

#CSR(Compressed Sparse Row) : COO보다 메모리 절약

In [16]:
#https://rfriend.tistory.com/551

row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])

sparse.csr_matrix((data, (row, col)), shape=(3, 3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]], dtype=int64)

In [17]:
indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])

sparse.csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [23]:
for i in range(3):
    print(indices[indptr[i]:indptr[i+1]])

[0 2]
[2]
[0 1 2]
